[".config/zsh/plugins/zsh-defer"]
  type = "archive"
  url = "https://github.com/romkatv/zsh-defer/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".config/zsh/plugins/fast-syntax-highlighting"]
  type = "archive"
  url = "https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".config/zsh/plugins/zsh-autocomplete"]
  type = "archive"
  url = "https://github.com/marlonrichert/zsh-autocomplete/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".config/zsh/plugins/zsh-autosuggestions"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
