#!/bin/sh

alias docker=podman
alias code=code-insiders
alias cz=chezmoi
alias reload!='. ~/.zshrc'
alias cls='clear' # Good 'ol Clear Screen command
alias -g -- -h='-h 2>&1 | bat --language=help --style=plain'
alias -g -- --help='--help 2>&1 | bat --language=help --style=plain'

# get erlang version
alias erlv="erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), \"releases\", erlang:system_info(otp_release), \"OTP_VERSION\"])), io:fwrite(Version), halt().' -noshell"
